name: Mi Workflow

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  first-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Configuracion de Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Python script
        run: python hello.py